import React from 'react';

export default function Head() {
  return (
    <>
      <title> About page</title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by create speedy" />
      <link rel="icon" href="/favicon.ico" />
    </>
  );
}
